[workspace]
members = ["crates/*"]
exclude = ["fuzz"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.97"
license = "MIT OR Apache-2.0"
repository = "https://github.com/astral-sh/astral-mail-headers"

[workspace.dependencies]
criterion = { package = "codspeed-criterion-compat", version = "=5.0.1", default-features = false, features = ["cargo_bench_support"] }
mailparse = { version = "=0.16.1", default-features = false }
rustc-hash = { version = "2.0.0", default-features = false, features = ["std"] }
serde = { version = "1.0", default-features = false, features = ["derive", "std"] }
base64 = { version = "0.22.1", default-features = false, features = ["alloc"] }
memchr = { version = "2.7.4", default-features = false, features = ["std"] }
serde_json = { version = "1.0", default-features = false, features = ["std"] }
simdutf8 = { version = "0.1.5", default-features = false, features = ["std", "aarch64_neon"] }
stats_alloc = "0.1.10"

[workspace.lints.rust]
unsafe_code = "forbid"
unreachable_pub = "warn"
missing_docs = "warn"

[workspace.lints.clippy]
dbg_macro = "warn"

[profile.release]
lto = "thin"
codegen-units = 1

[profile.profiling]
inherits = "release"
debug = true
