[package]
name = "astral-email-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[workspace]
members = ["."]

[dependencies]
astral-email = { path = "../crates/astral-email" }
libfuzzer-sys = "0.4"
serde_json = { version = "1.0", default-features = false, features = ["std"] }

[[bin]]
name = "reader"
path = "fuzz_targets/reader.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode"
path = "fuzz_targets/decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "lookup"
path = "fuzz_targets/lookup.rs"
test = false
doc = false
bench = false

[[bin]]
name = "python"
path = "fuzz_targets/python.rs"
test = false
doc = false
bench = false
